# Model Configuration
embed_model: "BAAI/bge-large-en-v1.5"
frame_interval: 5 # Interval between frames in seconds

# Directory Configuration
indexing_path: "db/mm_index"
data_dir: "db/datafiles"
video_dir: "db/video"

# Retrieval Configuration
similarity_top_k: 5
image_similarity_top_k: 5

# Gemini Configuration
gemini_api_key: "<token>" # Replace with your actual API key

# Video Processing Configuration
max_frames: 10000 # Maximum number of frames to extract
min_segment_length: 2 # Minimum segment length in seconds
max_segment_length: 10 # Maximum segment length in seconds

# UI Configuration
max_display_frames: 6 # Maximum number of frames to display in UI
frame_display_columns: 3 # Number of columns for frame display grid
